handshake-org/handshake-org.github.io

files/handshake.txt

Address minor issues with the paper at `files/handshake.txt`:
* Fix what look like typos to me. I'm not an expert editor so I'd check these changes carefully to be sure you agree.
* Consistently hard wrap to 80 characters in body. Previously almost every line was hard wrapped to 80 characters, so I assume this is the intent.
* Make the document valid UTF-8. This is the encoding required by the header at `https://handshake-org.github.io/files/handshake.txt`: `Content-Type: text/plain; charset=utf-8`. Previously some accent marks were not valid UTF-8. Validity was checked with ` iconv -f UTF-8 files/handshake.txt > /dev/null` on Mac.

Address minor issues with files/handshake.txt

---

src/guides/events.md

Adds events and sockets guide/chart to Handshake docs.
I think I got all the replace `bcoin` -> `handshake` stuff right, but needs review. Also have not run the example scripts against actual `hsd` or `hsd-cli` yet
In the doc I reference creating a strong API key, which is described in bcoin.io API docs but not handshake yet. Here's that blob: https://github.com/bcoin-org/bcoin-org.github.io/pull/110
Also just a quick cntrl+F `'emit'` on handshake library, looks like there's only one new event maybe worth adding -- `claim`: https://github.com/handshake-org/hsd/blob/master/lib/mempool/mempool.js#L1014
Waddaya think @boymanjor lemme know if I need to tweak anything else.

Guides: Events and Sockets

---

src/api-docs/source/includes/_wallet.md

Updates the wallet options in api-docs.
Specifically, the CLI params for watch-only and account-key. Those params were
[changed](https://github.com/bcoin-org/bclient/commit/4f8597d512c142e10ec678e2e0daea70a20ce048) [twice](https://github.com/bcoin-org/bclient/commit/0fa8536f552c091d777bfbbd62c6167929c782dd) in `bclient` (and bcoin docs are up to date) but in hs-client the params remain how they were originally:
https://github.com/handshake-org/hs-client/blob/98462eb180555298c50c453cf37a9d795006cdc5/bin/hsw-cli#L85-L86

api-docs: update wallet options

---

src/guides/win-install.md

When I overwrite below text
"<!(bash -c \"python -c 'from __future__ import print_function; import sys; print(sys.byteorder)'\")",
then, error was output :
File "<string>", line 1
'from
^
SyntaxError: EOL while scanning string literal
And I replaced ' to \" , it worked.

Enable overwriting to work

---

src/guides/auctions.md

With the new resource serialization format, the API syntax for the `sendupdate` CLI command has changed. Reflect that in the guide.

guides: revise sendupdate in auction guide

---

src/api-docs/source/includes/_node_rpc_tx.md

A few updates:
nulldata messages must be hex-encoded bwtween 2 and 40 bytes
(to conform to the rules of bech32, this is NOT an OP_RETURN)
HSD doesn't have scriptPubkey because everything is segwit, the
correct parameter name is `address`
In cURL, variables with numerical values are simply single-quoted

api-docs: fix create/sign rawtransaction

---

README.md

Now that `python2` is no longer being maintained, this PR adds to the `README` how to serve the docs using `python3`. It makes no assumptions about what the python executable is called and assumes the user will be able to figure out which version they are running.

readme: quickfix

---

api-docs/index.html
guides/events.html
src/api-docs/source/includes/_node.md

Adds the Node HTTP endpoint `GET /header/hashOrHeight` to the docs.
PR here:
https://github.com/handshake-org/hsd/pull/210

api: get block header

---

api-docs/index.html
guides/events.html
src/api-docs/source/includes/_node_rpc_names.md

This adds docs for the node RPC method `getdnssecproof` that is implemented here: https://github.com/handshake-org/hsd/pull/261
The logic for this is located here: https://github.com/chjj/bns/blob/master/lib/ownership.js#L735

node rpc: add getdnssecproof

---

README.md

Really quick additional guideline added to the `README` about not including any built files in PRs.

readme: pr guideline, do not build

---

src/guides/config.md

Closes https://github.com/handshake-org/handshake-org.github.io/issues/72
the sample hsd.conf was removed in https://github.com/handshake-org/hsd/commit/299aa7b3e6189a006a03dfe1f229d171195c9028

guides: remove sample hsd.conf from configuration guide

---

src/api-docs/source/includes/_coin.md
src/api-docs/source/includes/_node.md
src/api-docs/source/includes/_node_rpc.md
src/api-docs/source/includes/_node_rpc_block.md
src/api-docs/source/includes/_node_rpc_chain.md
src/api-docs/source/includes/_node_rpc_general.md
src/api-docs/source/includes/_node_rpc_mempool.md
src/api-docs/source/includes/_node_rpc_mining.md
src/api-docs/source/includes/_node_rpc_names.md
src/api-docs/source/includes/_node_rpc_network.md
src/api-docs/source/includes/_node_rpc_tx.md
src/api-docs/source/includes/_transaction.md
src/api-docs/source/includes/_wallet.md
src/api-docs/source/includes/_wallet_accounts.md
src/api-docs/source/includes/_wallet_admin.md
src/api-docs/source/includes/_wallet_auctions.md
src/api-docs/source/includes/_wallet_rpc.md
src/api-docs/source/includes/_wallet_tx.md
src/api-docs/source/index.html.md
src/api-docs/source/stylesheets/_variables.scss

I added a long intro to the API docs covering most of the FAQs we get from new developers using the hsd API for the first time.
In addition, I replaced all the curl $url stuff with the explicit path. It's too hard to find what $url stores in the docs, and it makes the examples impossible to copy-paste unless you've already set the environment variable

api-docs: expand intro and drop curl url environment variable

---

src/guides/resource-records.md

Since most handshake users will just be interested in getting a website online for their new name, this guide should clarify that for regular DNS records like A, AAAA, CNAME, etc. a conventional nameserver is necessary for the chain to refer to.

Clarify that a nameserver is needed

---

src/api-docs/source/includes/_clients.md

https://hsd-dev.org/api-docs/#using-javascript-clients,  Connecting to nodes that have SSL( https) enabled is using hs-client needs to be specified in the API documentation as seen in the guide https://hsd-dev.org/guides/config.html

Add ssl to javascript client connection

---

src/api-docs/source/includes/_wallet_rpc.md
src/api-docs/source/index.html.md

Move explanation of "unconfirmed" to intro section.
It closes #94.

api-docs: bump explanation of unconfirmed to intro section

---

src/api-docs/source/includes/_clients.md
src/api-docs/source/includes/_coin.md
src/api-docs/source/includes/_node.md
src/api-docs/source/includes/_node_rpc.md
src/api-docs/source/includes/_node_rpc_block.md
src/api-docs/source/includes/_node_rpc_chain.md
src/api-docs/source/includes/_node_rpc_general.md
src/api-docs/source/includes/_node_rpc_mempool.md
src/api-docs/source/includes/_node_rpc_mining.md
src/api-docs/source/includes/_node_rpc_names.md
src/api-docs/source/includes/_node_rpc_network.md
src/api-docs/source/includes/_node_rpc_tx.md
src/api-docs/source/includes/_node_sockets.md
src/api-docs/source/includes/_transaction.md
src/api-docs/source/includes/_wallet.md
src/api-docs/source/includes/_wallet_accounts.md
src/api-docs/source/includes/_wallet_admin.md
src/api-docs/source/includes/_wallet_auctions.md
src/api-docs/source/includes/_wallet_rpc.md
src/api-docs/source/includes/_wallet_rpc_auctions.md
src/api-docs/source/includes/_wallet_sockets.md
src/api-docs/source/includes/_wallet_tx.md
src/api-docs/source/index.html.md
src/guides/events.md

Remove unused 'network' option passed to Javascript clients.
It closes #92

Remove 'network' from options passed to Javascript clients.

---

src/api-docs/source/includes/_node_rpc_names.md

api-docs: Fix outdated rpc getnameresource example.
It closes https://github.com/handshake-org/handshake-org.github.io/issues/83.

api-docs: Fix outdated rpc getnameresource example.

---

.gitignore
bin/build

I noticed when you try to run `./bin/build` it will try to install dependencies, but on my machine (Not sure about others)
it tries to install in system folder, which then requires su to have access.
So this is the fix for that issue.
Also `.bundle` is generated at `src/api-docs/.bundle` if you specify custom `vendor`.

Bundle installing dependencies

---

src/guides/linux-install.md
src/guides/linux-install_sp.md
src/guides/mac-install.md
src/guides/mac-install_sp.md
src/guides/win-install.md
src/guides/win-install_sp.md

Should've been done along with https://github.com/handshake-org/hsd/commit/0a5a2608e86baf39145ae5528008082e505b5b3a (during https://github.com/handshake-org/hsd/pull/663).

Fix hsd installation doc URLs

---

.github/workflows/deploy.yml

See https://github.com/handshake-org/handshake-org.github.io/pull/165.

Use the same Ruby version in CI and Gemfile.lock

---

src/api-docs/source/includes/_node.md
src/api-docs/source/includes/_wallet.md
src/api-docs/source/includes/_wallet_accounts.md
src/api-docs/source/includes/_wallet_admin.md
src/api-docs/source/includes/_wallet_auctions.md
src/api-docs/source/includes/_wallet_rpc_auctions.md
src/api-docs/source/includes/_wallet_tx.md
src/api-docs/source/stylesheets/_custom.scss

Update things that have changed according to the CHANGELOG.

Update api-docs to v7

---

src/protocol/summary.md

The old revoke summary was not very clear about when someone can reopen the domain for auction after a revoke.
> A revoked name can be re-opened with a new auction after it expires, but the current chain of ownership is terminated.
This seems to say the auction can only be opened 2 years after the previous heartbeat (aka the domain expires)
@rithvikvibhu double checked this in the code and the domain is ready to auction after only ~29 days from the revoke
The check to see if the domain is ready to auction uses `AuctionMaturity`:
> height < this.revoked + network.names.auctionMaturity
From https://github.com/handshake-org/hsd/blob/0a4f24bdb0cc93b1d0236c77966085b305fe3d71/lib/covenants/namestate.js#L203
And `AuctionMaturity` is:
> auctionMaturity: (5 + 10 + 14) * main.pow.blocksPerDay
From …

protocol: Clarify revoked name delay in summary.md

---

src/guides/config.md

- closes #158 
- adds missing pool options
- removes unused option `selfish` (https://github.com/handshake-org/hsd/pull/860)

config: update pool options

---

src/api-docs/source/includes/_wallet_rpc_auctions.md

Add API docs for the sendbatch transaction from https://github.com/handshake-org/hsd/pull/686 to the Wallet RPC commands. All the other sendx rpc calls are in the auctions section so I've put the sendbatch there.

api-docs: Add sendbatch to wallet rpc calls
